name: OSCAL Pages CI/CD
on:
  push:
    branches:
    - main
    - develop
    - "feature-*"
    - "release-*"
  pull_request:
    branches:
    - main
    - develop
    - "feature-*"
    - "release-*"
  workflow_dispatch:
jobs:
  validate-website:
    uses: ./.github/workflows/workflow-generate-website.yml
    with:
      publish_website: false
  push-website:
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/workflow-generate-website.yml
    with:
      publish_website: true
    secrets:
      access_token: ${{ secrets.COMMIT_TOKEN }}